### ISSUE TITLE
rss feed?

### ISSUE THREAD

**Issue by charlieok** [SpiderOak/crypton-web#17]
I was interested in following your blog, but I'm not sure if I can add it to a feed reader. I didn't find an RSS feed when looking at the HTML, though I haven't looked through the actual source...

**Comment by ecto** [comment]
Just added one - does this work for you? https://crypton.io/blog/feed.xml

**Comment by charlieok** [comment]
Yup, thanks! That was quick :)

**Comment by ecto** [comment]
No problem!
