### ISSUE TITLE
Broken external link for Leviathan Security Group audit paper

### ISSUE THREAD

**Issue by fawkesley** [SpiderOak/crypton-web#25]
[This page](https://crypton.io/docs/security/audits.html) links to the [Leviathan Security Group audit](http://www.leviathansecurity.com/wp-content/uploads/Crypton_2014_pentest_Final_Report.pdf). Unfortunately the link appears to have been broken.

I searched the Wayback Machine and found [this PDF](http://web.archive.org/web/20150403175113/http://www.leviathansecurity.com/wp-content/uploads/SpiderOak-Crypton_pentest-Final_report_u.pdf) which I believe is the right one.

Ref: https://github.com/SpiderOak/crypton-web/commit/4b6b7d83a735381c77c09e525aeba1e3e75c9513

**Comment by daviddahl** [comment]
Yes, that is the correct audit report. Thanks!
